import Header from '@/app/(main)/layout/header';
import Sidebar, { MobileSideBar } from '@/app/(main)/layout/sidebar';
import { ThemeProvider } from '@/app/(main)/layout/theme-provider';
import { SidebarProvider } from '@/context/sidebar-context';
import type { Metadata } from 'next';

export const metadata: Metadata = {
    title: 'Koco',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
            <SidebarProvider>
                <div className="flex h-screen flex-col pb-4 overflow-hidden">
                    <Header />
                    <div className="min-h-full w-full flex flex-1  justify-center overflow-auto pb-4">
                        <div className="relative flex w-full max-w-[1480px] px-4 sm:px-6 lg:px-8">
                            <aside
                                className="hidden md:block fixed top-(--spacing-header) h-full overflow-y-auto 
                                w-sidebar flex-shrink-0 bg-background py-6 pb-20"
                            >
                                <Sidebar />
                            </aside>
                            <MobileSideBar />
                            <main className="w-full h-full ml-0 flex-1 py-6 md:pr-4 md:pl-8 md:ml-sidebar">
                                <div className="pb-20">{children}</div>
                            </main>
                        </div>
                    </div>
                </div>
            </SidebarProvider>
        </ThemeProvider>
    );
}
