import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';

import AuthProvider from '@/components/providers/auth-provider';
import SocketProvider from '@/components/providers/socket-provider';
import ToastProvider from '@/components/providers/toast-provider';

import './styles/globals.css';

const geistSans = Geist({
    variable: '--font-geist-sans',
    subsets: ['latin'],
});

const geistMono = Geist_Mono({
    variable: '--font-geist-mono',
    subsets: ['latin'],
});

export const metadata: Metadata = {
    title: 'Koco',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" suppressHydrationWarning>
            <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
                <AuthProvider>{children}</AuthProvider>
                <ToastProvider />
                <SocketProvider />
            </body>
        </html>
    );
}
